/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fpir;

import java.awt.Color;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.net.Socket;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Scanner;
import java.util.Set;
import java.io.*;
import java.lang.reflect.Array;
import java.util.Vector;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author user
 */
public class a extends javax.swing.JFrame {

    static Socket s;
    static DataInputStream din;
    static DataOutputStream dout;
    static DefaultTableModel model;
    /**
     * Creates new form a
     */
    public a() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        kesimpulan = new javax.swing.JLabel();
        analisis1 = new javax.swing.JLabel();
        navbar = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        form_input = new javax.swing.JTextField();
        tombol_simpan = new javax.swing.JButton();
        form_kesimpulan = new javax.swing.JTextField();
        akhir = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        goods = new javax.swing.JLabel();
        hates = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(875, 544));
        setResizable(false);

        sidebar.setBackground(new java.awt.Color(0, 102, 102));
        sidebar.setPreferredSize(new java.awt.Dimension(175, 166));

        kesimpulan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kesimpulan.setForeground(new java.awt.Color(255, 255, 255));
        kesimpulan.setText("Kesimpulan");
        kesimpulan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kesimpulan.setPreferredSize(new java.awt.Dimension(50, 17));
        kesimpulan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kesimpulanMouseClicked(evt);
            }
        });

        analisis1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        analisis1.setForeground(new java.awt.Color(255, 255, 255));
        analisis1.setText("Analisis");
        analisis1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        analisis1.setPreferredSize(new java.awt.Dimension(50, 17));
        analisis1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                analisis1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(analisis1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kesimpulan, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(analisis1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(kesimpulan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(470, Short.MAX_VALUE))
        );

        navbar.setBackground(new java.awt.Color(0, 102, 102));
        navbar.setPreferredSize(new java.awt.Dimension(409, 44));

        judul.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 255, 255));
        judul.setText("ANALISIS SENTIMEN #HATESPEECH PADA TWITTER");

        javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
        navbar.setLayout(navbarLayout);
        navbarLayout.setHorizontalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navbarLayout.createSequentialGroup()
                .addContainerGap(290, Short.MAX_VALUE)
                .addComponent(judul)
                .addGap(272, 272, 272))
        );
        navbarLayout.setVerticalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(judul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        tombol_simpan.setBackground(new java.awt.Color(255, 255, 255));
        tombol_simpan.setText("Simpan");
        tombol_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_simpanActionPerformed(evt);
            }
        });

        form_kesimpulan.setEditable(false);

        akhir.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(tombol_simpan)
                            .addGap(106, 106, 106)
                            .addComponent(akhir, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(form_input, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                        .addComponent(form_kesimpulan, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(hates, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goods, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(navbar, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(form_input, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tombol_simpan)
                            .addComponent(akhir, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(goods, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hates, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(form_kesimpulan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kesimpulanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kesimpulanMouseClicked
        // TODO add your handling code here:
        form_kesimpulan.setVisible(true);
        form_input.setVisible(true);
        //form_input.setEditable(false);
        tombol_simpan.setVisible(false);

    }//GEN-LAST:event_kesimpulanMouseClicked

    private void tombol_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_simpanActionPerformed
        String good ="DATA/unigram_goodspeech.txt"; 
	String hate ="DATA/unigram_hatespeech.txt"; 
	String input ="DATA/input.txt"; 
	String cgood= null; 
	String chate= null; 
	String cinput= null; 
        
	String oj ="DATA/hasil_unigram_akhir.txt"; 
	String ok= null; 
        try {
            File inputkosong = new File("DATA/input.txt"); 
            PrintWriter pkalnullkosong = new PrintWriter(new FileWriter(inputkosong, false));
            pkalnullkosong.println();
            
            File proseskosong = new File("DATA/proses_input_unigram.txt"); 
            PrintWriter prosesnullkosong = new PrintWriter(new FileWriter(proseskosong, false));
            prosesnullkosong.println();
            
            File unigram_awal = new File("DATA/hasil_unigram_awal.txt"); 
            PrintWriter prosesnullunigram_awal = new PrintWriter(new FileWriter(unigram_awal, false));
            prosesnullunigram_awal.println();
            
            String kalmat; 
            kalmat = form_input.getText(); 
            File datakal9 = new File("DATA/input.txt"); 
            PrintWriter pkal9 = new PrintWriter(new FileWriter(datakal9, true)); 
            pkal9.println(kalmat); 
            pkal9.close();
            
            cinput = new String(Files.readAllBytes(Paths.get(input)));
            String kecil9 = cinput.toLowerCase(); 
            String simbol9 = kecil9.replaceAll("[^\\p{L}\\s]", "");  //  \\p{M}\\p{N}\\p{P}\\p{Z}\\p{Cf}\\p{Cs}
            String[] fkal9 = simbol9.split("\\s+");
            
            cgood = new String(Files.readAllBytes(Paths.get(good)));
            chate = new String(Files.readAllBytes(Paths.get(hate)));
            for(String hukal9 : fkal9) { 
                boolean sapigood = cgood.contains(hukal9); 
                boolean sapihate = chate.contains(hukal9); 
                if (sapigood){ 
                    File datasapigood = new File("DATA/proses_input_unigram.txt"); 
                    PrintWriter prsapigood = new PrintWriter(new FileWriter(datasapigood, true)); 
                    prsapigood.println(hukal9); 
                    prsapigood.close(); 
                    // durung iso nge print
                    String textgood = "goodspeech"; 
                    File hasil_unigram_awal = new File("DATA/hasil_unigram_awal.txt"); 
                    PrintWriter prtextgood = new PrintWriter(new FileWriter(hasil_unigram_awal, true)); 
                    prtextgood.println(textgood);
                    prtextgood.close();
                    
                    BufferedReader listigood = new BufferedReader (new FileReader("DATA/hasil_unigram_awal.txt")); 
                    boolean hasdigood = true;
                    String lineigood; 
                    Set<String> linesigood = new HashSet<String>(); 
                    while ((lineigood = listigood.readLine()) != null) { 
                        if (linesigood.contains(lineigood)) { 
                            hasdigood = false; 
                        }
                        linesigood.add(lineigood);
                    }
                    if (hasdigood) { 
                        File dataindgood = new File("DATA/hasil_unigram_akhir.txt"); 
                        PrintWriter prinddataindgood = new PrintWriter(new FileWriter(dataindgood, false)); 
                        prinddataindgood.println(textgood);
                        prinddataindgood.close();  
                    }
                    
                } else if (sapihate){ 
                    File datasapihate = new File("DATA/proses_input_unigram.txt"); 
                    PrintWriter prsapihate = new PrintWriter(new FileWriter(datasapihate, true)); 
                    prsapihate.println(hukal9); 
                    prsapihate.close(); 
                    // durung iso nge print
                    String texthate = "hatespeech"; 
                    File hasil_unigram_awal = new File("DATA/hasil_unigram_awal.txt"); 
                    PrintWriter prtexthate = new PrintWriter(new FileWriter(hasil_unigram_awal, true)); 
                    prtexthate.println(texthate); 
                    prtexthate.close();
                      
                    BufferedReader listihate = new BufferedReader (new FileReader("DATA/hasil_unigram_awal.txt")); 
                    boolean hasdihate = true;
                    String lineihate; 
                    Set<String> linesihate = new HashSet<String>(); 
                    while ((lineihate = listihate.readLine()) != null) { 
                        if (linesihate.contains(lineihate)) { 
                            hasdihate = false; 
                        }
                        linesihate.add(lineihate);
                    }
                    if (hasdihate) { 
                        File dataindhate = new File("DATA/hasil_unigram_akhir.txt"); 
                        PrintWriter prinddataindhate = new PrintWriter(new FileWriter(dataindhate, false)); 
                        prinddataindhate.println(texthate);
                        prinddataindhate.close();  
                    }
                }
            } //for
                ok = new String(Files.readAllBytes(Paths.get(oj)));
                akhir.setText(ok); 
                
            String jgood ="DATA/unigram_goodspeech.txt"; 
            String pjgood= null; 
            pjgood = new String(Files.readAllBytes(Paths.get(jgood)));
            String[] opjgood = pjgood.split("\\s+"); // bawah
            int Barisjgood  = opjgood.length; 
            String jumlahBarisjgood  = Integer.toString(Barisjgood);
            goods.setText(jumlahBarisjgood);
            
            String jhate ="DATA/unigram_hatespeech.txt"; 
            String pjhate= null; 
            pjhate = new String(Files.readAllBytes(Paths.get(jhate)));
            String[] opjhate = pjhate.split("\\s+"); // bawah
            int Barisjhate  = opjhate.length; 
            String jumlahBarisjhate  = Integer.toString(Barisjhate);
            hates.setText(jumlahBarisjhate);
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_tombol_simpanActionPerformed

    private void analisis1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_analisis1MouseClicked
        // TODO add your handling code here:
        form_input.setVisible(true);
        tombol_simpan.setVisible(true);
        form_kesimpulan.setVisible(false);
       // form_input.setEditable(true);
    }//GEN-LAST:event_analisis1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold> 
        
        String data_mentah ="DATA/data_goodspeech.txt"; 
	String data_mentahhate ="DATA/data_hatespeech.txt"; 
	String stopword_list_tala ="DATA/stopwocrd_list_tala.txt"; 
	String cdata_mentah= null; 
	String cdata_mentahhate= null; 
	String cstopword_list_tala= null; 
        
	String tala ="DATA/stopword_list_tala.txt"; 
	String ctala= null; 
        try {
            
            File inputkosong = new File("DATA/input.txt"); 
            PrintWriter pkalnullkosong = new PrintWriter(new FileWriter(inputkosong, false));
            pkalnullkosong.println();
            
            File proseskosong = new File("DATA/proses_input_unigram.txt"); 
            PrintWriter prosesnullkosong = new PrintWriter(new FileWriter(proseskosong, false));
            prosesnullkosong.println();
            
            File unigram_awal = new File("DATA/hasil_unigram_awal.txt"); 
            PrintWriter prosesnullunigram_awal = new PrintWriter(new FileWriter(unigram_awal, false));
            prosesnullunigram_awal.println();
            
            // GOOD-SPEECH men set file input menjadi kosong
            File inputnull = new File("DATA/unigram_goodspeech_tanpa_contains.txt"); 
            PrintWriter pkalnull = new PrintWriter(new FileWriter(inputnull, false)); 
            pkalnull.println(); //print data
            cdata_mentah = new String(Files.readAllBytes(Paths.get(data_mentah))); 
            String kecili = cdata_mentah.toLowerCase(); 
            String simbol = kecili.replaceAll("[^\\p{L}\\s]", "");  //  \\p{M}\\p{N}\\p{P}\\p{Z}\\p{Cf}\\p{Cs}
            String[] fkal = simbol.split("\\s+"); 
            //cstopword_list_tala = new String(Files.readAllBytes(Paths.get(stopword_list_tala))); //yg eror pake stopword
            ctala = new String(Files.readAllBytes(Paths.get(tala)));
            for(String hukal : fkal) { 
             //  boolean ikan = hukal.contains(hukal); 
               boolean ikan = ctala.contains(hukal);  
               if (!ikan){ 
                File dataindonesia = new File("DATA/unigram_goodspeech_tanpa_contains.txt"); 
                PrintWriter prindonesia = new PrintWriter(new FileWriter(dataindonesia, true)); 
                prindonesia.println(hukal); 
                prindonesia.close();  
                }
            }
            
            // HATE-SPEECH men set file input menjadi kosong
            File inputnullhate = new File("DATA/unigram_hatespeech_tanpa_contains.txt"); 
            PrintWriter pkalnullhate = new PrintWriter(new FileWriter(inputnullhate, false)); 
            pkalnullhate.println(); //print data
            cdata_mentahhate = new String(Files.readAllBytes(Paths.get(data_mentahhate))); 
            String kecilihate = cdata_mentahhate.toLowerCase(); 
            String simbolhate = kecilihate.replaceAll("[^\\p{L}\\s]", "");  //  \\p{M}\\p{N}\\p{P}\\p{Z}\\p{Cf}\\p{Cs}
            String[] fkalhate = simbolhate.split("\\s+"); 
            //cstopword_list_tala = new String(Files.readAllBytes(Paths.get(stopword_list_tala)));
            ctala = new String(Files.readAllBytes(Paths.get(tala)));
            for(String hukalhate : fkalhate) { 
               boolean ikanhate = ctala.contains(hukalhate); 
               if (!ikanhate){ 
                File datahate = new File("DATA/unigram_hatespeech_tanpa_contains.txt"); 
                PrintWriter prhate = new PrintWriter(new FileWriter(datahate, true)); 
                prhate.println(hukalhate); 
                prhate.close(); 
                }
            }
            
            //  MENGHAPUS DATA YANG SAMA ANTARA unigram_goodspeech.txt DENGAN unigram_hatespeech.txt
            
            String z ="DATA/unigram_goodspeech_tanpa_contains.txt"; 
            String za= null; 
            za = new String(Files.readAllBytes(Paths.get(z)));
            String[] zaqbawah = za.split("\\s+"); // bawah
            String[] zaq = za.split("\\s+", 1); // datar
            
            String x ="DATA/unigram_hatespeech_tanpa_contains.txt"; 
            String xs= null; 
            xs = new String(Files.readAllBytes(Paths.get(x)));
            String[] xswbawah = xs.split("\\s+"); // bawah
            String[] xsw = xs.split("\\s+", 1);//datar
            
            //  goodspeech contains hatespeech = goospeech
            File bakarnul = new File("DATA/unigram_goodspeech.txt"); 
            PrintWriter pkabakarnul = new PrintWriter(new FileWriter(bakarnul, false)); 
            pkabakarnul.println(); 
            for(String siputgood : zaqbawah) {   // string : split
            boolean siputbakar = xs.contains(siputgood);   // bawah contains datar
                if(!siputbakar){
                    File zaq1 = new File("DATA/unigram_goodspeech.txt"); 
                    PrintWriter zaq10 = new PrintWriter(new FileWriter(zaq1, true)); 
                    zaq10.println(siputgood); 
                    zaq10.close();
                }
            }
            //  hatespeech contains goodspeech = hatespeech
            File gorengnul = new File("DATA/unigram_hatespeech.txt"); 
            PrintWriter pkagorengnul = new PrintWriter(new FileWriter(gorengnul, false)); 
            pkagorengnul.println(); 
            for(String siputhate : xswbawah) {   // string : split
            boolean siputgoreng = za.contains(siputhate);   // bawah contains datar
                if(!siputgoreng){
                    File xsw1 = new File("DATA/unigram_hatespeech.txt"); 
                    PrintWriter xsw10 = new PrintWriter(new FileWriter(xsw1, true)); 
                    xsw10.println(siputhate); 
                    xsw10.close();
                }
            }
            

        } catch (IOException ex) {
            Logger.getLogger(a.class.getName()).log(Level.SEVERE, null, ex);
        }
	
       
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new a().setVisible(true);
                form_kesimpulan.setVisible(false);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel akhir;
    private javax.swing.JLabel analisis1;
    private static javax.swing.JTextField form_input;
    private static javax.swing.JTextField form_kesimpulan;
    private javax.swing.JLabel goods;
    private javax.swing.JLabel hates;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel kesimpulan;
    private javax.swing.JPanel navbar;
    private javax.swing.JPanel sidebar;
    private static javax.swing.JButton tombol_simpan;
    // End of variables declaration//GEN-END:variables
}
